do not download when licence is not set
gpslab/geoip2 pull request #91
Opened 2024-10-27 01:48 UTC by antedebaas

I needed the bundle not fail in the command because a license has not been set
for my project there are use cases where a license will not be used (its up to the user)
this pr will instead of blindly try a download show a warning when the license is not set and skip the download step.

2024-11-18 19:14 UTC, peter-gribanov requested changes

2024-11-18 19:14 UTC, peter-gribanov commented on src/Command/UpdateDatabaseCommand.php
> +                $io->warning(sprintf('`GeoIP Database %s has no maxmind license key', $database));
Please remove the backticks from the message.
```diff
-'`GeoIP Database %s has no maxmind license key'
+'GeoIP Database %s has no maxmind license key'
```

2024-11-18 19:14 UTC, peter-gribanov commented on src/Command/UpdateDatabaseCommand.php
>              $io->comment(sprintf('Database <info>%s</info> updated', $database));
Please move this line after `$this->downloader->download()`. It is necessary to write about the success of the database update only if it was actually successfully updated.

2024-11-18 19:17 UTC, peter-gribanov commented
Thanks for the PR :+1: Please fix the unit tests.

2024-11-18 20:01 UTC, antedebaas commented on src/Command/UpdateDatabaseCommand.php
> +                $io->warning(sprintf('`GeoIP Database %s has no maxmind license key', $database));
fixed

2024-11-18 20:01 UTC, antedebaas commented on src/Command/UpdateDatabaseCommand.php
>              $io->comment(sprintf('Database <info>%s</info> updated', $database));
done

2024-11-18 20:02 UTC, antedebaas commented
@peter-gribanov updated the tests and added a new test for a case without license

2024-11-19 09:53 UTC, peter-gribanov approved these changes

2024-11-19 09:54 UTC, peter-gribanov commented
Good job :+1: Thank you.

2024-11-19 09:54 UTC, merged

2024-11-19 10:01 UTC, peter-gribanov commented
@antedebaas your feature published in [Release 2.1.2](https://github.com/gpslab/geoip2/releases/tag/v2.1.2)

2024-11-19 10:10 UTC, antedebaas commented
thanks